server:
  port: 8080

spring:
  data:
    redis:
      repositories:
        enabled: false
      host: 192.168.112.129
      port: 36379
      database: 0
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY:sk-5b7957a0c44c4532a27cac4276a63178}
      base-url: https://api.deepseek.com
      embedding:
        base-url: https://api.siliconflow.cn/v1
        api-key: sk-txztqxrurpokqgwugcwcdhumwqwsrnosawwrbiuqysthlygo
        embeddings-path: /embeddings
        options:
          model: BAAI/bge-large-zh-v1.5
          encoding-format: float
          dimensions: 1536
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
          max-tokens: 2048
          top-p: 0.9
          frequency-penalty: 0.1
          presence-penalty: 0.1
    vectorstore:
      redis:
        prefix: "default:"
        initialize-schema: true
        index-name: default-index
    mcp:
      server:
        # 基础配置
        enabled: true
        stdio: false
        name: mcp-server
        version: 1.0.0
        instructions: 基于 DeepSeek 的 AI 助手服务器，支持智能对话、工具调用和资源管理
        type: SYNC

        # URL 配置
#        base-url: /tools
#        sse-endpoint: /mcp/sse
#        sse-message-endpoint: /mcp/message

        # 功能能力配置
        capabilities:
          resource: true
          tool: true
          prompt: true
          completion: true

        # 通知配置
        resource-change-notification: true
        prompt-change-notification: true
        tool-change-notification: true

        # 工具响应类型配置
        tool-response-mime-type:
          generateImage: image/png
          generateDocument: application/pdf
          analyzeData: application/json
          processText: text/plain
          generateCode: text/x-java-source

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有端点
      base-path: /actuator
  endpoint:
    health:
      show-details: always

